// Modern icon set powered by lucide-react.
// Kept behind an `Icons.*` facade so pages don't depend on lucide names directly.
import {
  LayoutDashboard,
  BookOpen,
  Users,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  Settings,
  Megaphone,
  BarChart3,
  Plus,
  LogOut,
  Menu,
  X,
  GraduationCap,
  ChevronRight,
  KeyRound,
  Printer,
  Search,
  Clock,
  MapPin,
  Wallet,
  Download,
  UserCog,
  CircleCheck,
  Inbox,
} from 'lucide-react';

export const Icons = {
  dashboard: LayoutDashboard,
  book: BookOpen,
  users: Users,
  calendar: CalendarDays,
  check: ClipboardCheck,
  clipboard: ClipboardList,
  settings: Settings,
  megaphone: Megaphone,
  chart: BarChart3,
  plus: Plus,
  logout: LogOut,
  menu: Menu,
  close: X,
  cap: GraduationCap,
  chevronRight: ChevronRight,
  key: KeyRound,
  printer: Printer,
  search: Search,
  clock: Clock,
  pin: MapPin,
  wallet: Wallet,
  download: Download,
  userCog: UserCog,
  circleCheck: CircleCheck,
  inbox: Inbox,
};
